### PR TITLE
Feature.xe4 support2

### PR DESCRIPTION
**Pull request by yonojoy**
This is a replacement for pull request #17. All the JSON code is stuffed into one file.

### CODE REVIEW

**Comment by wlandgraf** [comment]
Thank you, but still, OpenAPIJSON has too many differences. The idea is not to separate into classes and create abstract methods, but just add IFDEF where needed. Just keep the way the code was before, just add IFDEF where needed, without refactoring the classes.

Could you please do that?

Also, there are new modifications in OpenApiUtils.pas, it would be good to merge those changing into the pull request to avoid conflicts.

**Comment by yonojoy** [comment]
That's what I said in the first place: The two/three implementations do not share enough code to satisfy a common base class (other than an abstract base), therefore my first implementation with 3 distinct implementations and the trick to ifdef the right one in (to avoid the extra code for abstract base class). This way it is easy to see, what to do to support an other json lib. And if you compare `OpenApiJson.pas` with `OpenApiJsonWrapper.pas` you'll see, that the wrapper code for System.JSON is untouched. If you compare `OpenApiJson.pas` with `OpenApiJsonWrapperFpc.pas` you'll see, that the code for this is untouched, too. (In svn you would have seen this right away - git is shitty compared to svn in this area).

I understood your argument to have everything in one file (from a marketing perspective), therefore I followed your proposal and spent my time to stuff everything into `OpenApiJson.pas`. 

You wrote:
> Keeping separated classes is fine if you can have a single ancestor that share the common code, with virtual
> methods, and for descendant classes only override and implement the differences. Is this possible?

I have done that.

But now you write:
> Thank you, but still, OpenAPIJSON has too many differences. The idea is not to separate into classes and create 
> abstract methods, but just add IFDEF where needed.

Sorry, I am out at this point. I highly appreciate the work you did with openapi-delphi-generator and wanted to give something back. But reading your arguments, I think it is better to stay with your current implementation. Not that many developers will have to support such an old Delphi version. And if they have to, they can refer to my pull request. This way your wrapper class stays readable.

When programming, I always try to do the right thing: In this case your wrapper class is a bridge pattern. Normally you would have an abstract base class and two or three classes implementing the bridge. I have provided two variations of this idea. But -sorry- I am not willing to provide an implementation based on ifdefs.
If you ever decide to add support for another JSON lib, I think you'll remember this conversation.

What should we do?

* I will close pull request #20 and 
* I would reopen pull request #17 (because I think that is the right implementation).

* You could merge pull request #15, then issue #14 should be fixed. The changes in `OpenApiUtils.pas`:
    > Also, there are new modifications in OpenApiUtils.pas, it would be good to merge those changing into the
    > pull request to avoid conflicts.

  stem from this pull request. The additional lines were needed, because I could not refer to OpenApiHttp in the uses section for Delphi <=XE7. 
  
* Anyone who needs support for Delphi <= XE7 should branch your repo and merge pull request #17 in his own repository.

**Comment by wlandgraf** [comment]
If you don't mind, I will get to implement XE4 support then based on your pull request #20.

**Comment by yonojoy** [comment]
Yes, please feel free to use the code however you want.

**Comment by wlandgraf** [comment]
@yonojoy, thank you very much for your contribution.
I was able to find time to review your changes, and now everything is applied (with the modifications you allowed me to do so).
Everything should be fixed and working, I'd appreciate if you could confirm everything is working one.

**Comment by yonojoy** [comment]
I tested your code. Everything seems to be fixed and working for XE4.

**Pull request merged**
