### PR TITLE
Add ability for Logging

### PR DESCRIPTION
**Pull request by yonojoy**
Resolves issue #27.

### CODE REVIEW

**Comment by yonojoy** [comment]
@wlandgraf Please be aware, that I am not able to compile `OpenApiHttp` with my Delphi version. Therefore the changes to this file are only out of my head and will likely contain errors.

**Comment by wlandgraf** [comment]
What is your Delphi version? What is the error you get with `OpenApiHttp`?

**Comment by yonojoy** [comment]
> What is your Delphi version? What is the error you get with `OpenApiHttp`?

XE4. Delphi does not provide System.Net.HttpClient and System.Net.URLClient (see issue #16). 
Therefore I can't compile this unit and cannot check, if everything works correctly.

**Comment by yonojoy** [comment]
This request is replaced by pull request #37

**Pull request closed without merging**
